# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='devlibrary/')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='devlibrary/')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='devlibrary/')),
                ('githublink', models.CharField(max_length=256)),
                ('websitelink', models.CharField(max_length=256)),
                ('rating', models.SmallIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
