# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
    ]
