# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlibrary', '0002_library_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.CharField(max_length=360),
        ),
    ]
